name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |

            cd /var/www/ICC343-ProyectoIntegrador-ClinicaDental

            git pull origin main

            docker compose down

            docker compose up -d --build

            docker exec clinica_app php artisan migrate --force

            docker exec clinica_app php artisan db:seed --class=RolSeeder --force

            docker exec clinica_app php artisan optimize
